name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t tradezon:${{ github.sha }} .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: |
          docker tag tradezon:${{ github.sha }} philipoyelegbin/tradezon:${{ github.sha }}
          docker push philipoyelegbin/tradezon:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into Cloud VM and Deploy App
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCP_HOST }}
          username: philip
          key: ${{ secrets.GCP_SSH_KEY_PRV }}
          script: |
            docker pull philipoyelegbin/tradezon:${{ github.sha }}
            docker stop runner1 || true
            docker rm runner1 || true
            docker run -d -p 3030:3000 --name runner1 philipoyelegbin/tradezon:${{ github.sha }}
